import { getHistoricByProjectId } from "./Audit";
import {
  getAllProject,
  getProjectByUserId,
  getAllLevelProjectByUserId,
  getProjectById,
  getProjectByIDs,
  createProject,
  updateProject,
  archiveProject,
  updateAdvancementProject,
  updateTeamProject,
  getPhaseById,
  updatePhaseSettings,
  getCountProject,
  updateProjectState,
  getProjectStat,
} from "./ProjectServices";

import {
  createTaskPhase,
  getTaskByProjectAndPhaseID,
  updateTaskProject,
  deletetaskProject,
} from "./TaskServices";

import {
  getAllActivitiesOfUser,
  getTransverseByUserId,
  getInterContractByUserId,
  createTransverse,
  updateTransverse,
  deleteTransverse,
  createInterContract,
  updateIntercontract,
  deleteIntercontract,
  getTaskActivityByUserId,
  createTaskActivity,
  updateTaskActicity,
  deleteTaskActivity,
  initializeSpaceRanking,
  getActivitiesStat,
  getActivitiesStatInAYear,
  getActivitiesPercentage,
} from "./Activities";
import {
  getAllMyNotification,
  updateNotifRead,
  MakeAllNotifReaded,
} from "./NotificationServices";

export {
  getAllProject,
  getProjectByUserId,
  getAllLevelProjectByUserId,
  getProjectById,
  getProjectByIDs,
  createProject,
  updateProject,
  archiveProject,
  updateAdvancementProject,
  getHistoricByProjectId,
  updateTeamProject,
  getPhaseById,
  updatePhaseSettings,
  createTaskPhase,
  getTaskByProjectAndPhaseID,
  updateTaskProject,
  deletetaskProject,
  getAllActivitiesOfUser,
  getTransverseByUserId,
  getInterContractByUserId,
  createTransverse,
  updateTransverse,
  deleteTransverse,
  createInterContract,
  updateIntercontract,
  deleteIntercontract,
  getTaskActivityByUserId,
  createTaskActivity,
  updateTaskActicity,
  deleteTaskActivity,
  getCountProject,
  updateProjectState,
  initializeSpaceRanking,
  getAllMyNotification,
  updateNotifRead,
  getActivitiesStat,
  getActivitiesStatInAYear,
  getActivitiesPercentage,
  getProjectStat,
  MakeAllNotifReaded,
};
